### ISSUE TITLE
Unexpected i/o error during a download ( in file "os.py " line 215 and 225)

### ISSUE THREAD

**Issue by u4y0u** [Stefal/mapillary_download#6]
```
downloading.. this process will take a while. please wait
Traceback (most recent call last):
  File "mapillary_download.py", line 148, in <module>
  File "os.py", line 215, in makedirs
  File "os.py", line 225, in makedirs
OSError: [Errno 5] Input/output error: 'data'
[28073] Failed to execute script 'mapillary_download' due to unhandled exception!
```

The error appeared following a request for 21 sequences, it was the first time that I exceeded 20.
So I thought it was too much, but the error persisted when I removed some id sequences...
I also thought it was a disk space problem, but that is far from the case since there was 4.5 TB free.
Nor even a problem with the right to create folders, I created and deleted other test folders in the open shell and I had used this same window for the same script for some time before.

**Comment by Stefal** [comment]
Is this bug still exists ?
